import numpy as np
m1=np.array([[[2,0,1],[3,6,2],[5,2,1]]])
m2=np.array([[[5,0,1],[1,2,3],[6,3,5]]])
print("Original 3-D matrix")
print(m1)
print(m2)
print("Sum of 2 matrix")
r=np.add(m1,m2)
print(r)
print("Difference of 2 matrix")
s=np.subtract(m1,m2)
print(s)
print("Product of 2 matrix")
p=np.multiply(m1,m2)
print(p)
